/* GENERATED by npm run derive from business.config.yaml — see 02-DERIVE-BRAIN.md. DO NOT HAND-EDIT.
 *
 * Fixes bugs A10/A11/A12. The reference dashboard kept its OWN copies of the
 * queue header (which drifted, so engine and dashboard writes reformatted the
 * file back and forth forever), of BUCKETS (11 entries vs the config's 8, so
 * validateTopic silently rejected valid topics), and of the publish cadence
 * (hardcoded Mon/Thu 09:00 America/Los_Angeles, so "next publish" lied the
 * moment anyone changed the schedule). They are generated from one source now.
 */
export const QUEUE_HEADER = "# Topic queue — the editorial backlog.\n# GENERATED by `npm run derive --only=queue`, then MUTATED BY THE ENGINE:\n#   dequeueTopic() removes the published topic; quarantineTopic() removes a failed one.\n# Reseed with `npm run derive --only=queue --append` (NEVER --force on a live repo —\n# that re-adds already-published and quarantined slugs and breaks the ledger invariant).\n# Hand-editing a topic's `notes` is expected and good; that is where quality comes from.\n\n";
export const BUCKETS = [
  "hyperlocal",
  "service-detail",
  "comparison",
  "question",
  "aftercare",
  "pricing",
  "first-timer",
  "eeat"
];
export const INTENTS = [
  "TOF / informational",
  "MOF / commercial",
  "BOF / transactional"
];
export const SERVICE_KEYS = [
  "haircut",
  "haircut-beard-trim",
  "beard-trim",
  "signature-haircut-black-mask",
  "hot-towel-shave",
  "scissor-cut-beard-trim"
];
export const PAGE_KEYS = [
  "about",
  "faq",
  "aftercare",
  "visit"
];
export const CADENCE_DAYS = [
  "Tuesday",
  "Friday"
];
export const PUBLISH_HOUR_LOCAL = "09:00";
export const TIMEZONE = "America/Los_Angeles";
export const LIVE_URL = "https://amirprecisioncuts.com";
export const BUSINESS_NAME = "Amir Precision Cuts";
export const AUTHOR_ID = "amir-precision-team";
