/**
 * constants.mjs — values that MUST be identical everywhere they appear.
 *
 * Fixes bug A10. In the reference build, `QUEUE_HEADER` was written out twice —
 * once in `pick-topic.mjs`, once in `dashboard/lib/constants.ts`. They drifted.
 * The result was a silent write war: every dashboard save reformatted the file
 * one way, every engine publish reformatted it back, and the queue churned in
 * git forever with no functional change to show for it.
 *
 * Bugs A11 (dashboard BUCKETS = 11 vs config buckets = 8, so `validateTopic`
 * silently rejected valid topics) and A12 (`nextScheduledPublish()` hardcoding
 * Mon/Thu 09:00 America/Los_Angeles) are the same disease. The cure is one
 * source: this file, plus `derive --only=dashboard` which emits a generated
 * TypeScript mirror of it so the Next.js app cannot hold a second opinion.
 */
import { cfg } from './paths.mjs';

/**
 * The header comment that sits atop queue.yaml. Deliberately free of business
 * facts and of references to any planning doc — the reference version mentioned
 * a "GAMEPLAN.md" that does not exist in this repo.
 */
export const QUEUE_HEADER =
  '# Topic queue — the editorial backlog.\n' +
  '# GENERATED by `npm run derive --only=queue`, then MUTATED BY THE ENGINE:\n' +
  '#   dequeueTopic() removes the published topic; quarantineTopic() removes a failed one.\n' +
  '# Reseed with `npm run derive --only=queue --append` (NEVER --force on a live repo —\n' +
  '# that re-adds already-published and quarantined slugs and breaks the ledger invariant).\n' +
  '# Hand-editing a topic\'s `notes` is expected and good; that is where quality comes from.\n\n';

/** YAML dump options — identical on every writer, or the file churns (A10). */
export const YAML_OPTS = { lineWidth: 100, noRefs: true, quotingType: '"' };

export const BUCKETS = cfg.content.buckets;

export const INTENTS = [
  'TOF / informational',
  'MOF / commercial',
  'BOF / transactional',
];

export const SERVICE_KEYS = cfg.services.map((s) => s.key);
export const PAGE_KEYS = ['about', 'faq', 'aftercare', 'visit'];

export const CADENCE_DAYS = cfg.content.cadence_days;
export const PUBLISH_HOUR_LOCAL = cfg.content.publish_hour_local;
export const TIMEZONE = cfg.location.timezone;
export const LIVE_URL = cfg.derived.site_url;

/** R19 / R1 — the loop limits. The reference had these in failure-classify.mjs only. */
export const MAX_TOPICS_PER_RUN = cfg.content.limits.max_topics_per_run;
export const MAX_REGEN_PER_TOPIC = cfg.content.limits.max_regen_per_topic;
export const MAX_API_CALLS_PER_RUN = cfg.content.limits.max_api_calls_per_run;
export const MAX_DERIVE_API_CALLS = cfg.content.limits.max_derive_api_calls;

/**
 * How many articles the sitemap, feed.xml, feed.json and llms.txt carry.
 *
 * Lives HERE, not in build-blog.mjs, because verify-live.mjs has to know it:
 * the blog index lists every article while these four are capped, so a
 * consistency check that compares them needs the cap to compute what "agreeing"
 * means. When it was a private const in build-blog.mjs, verify asserted
 * sitemap === cards and went red the moment a site published its 41st article
 * (§14 A1). Two files needing one number is exactly what constants.mjs is for.
 */
export const FEED_MAX = 40;
