#!/usr/bin/env node
/**
 * derive.mjs — the factory.
 *
 * `npm run derive` regenerates all SEVEN artifacts from business.config.yaml:
 *
 *   1. content/brand/voice.md              JUDGMENT   (one model call, then a human read)
 *   2. content/brand/forbidden.yaml        deterministic
 *   3. content/brand/internal-links.yaml   deterministic
 *   4. content/authors/<author_id>.yaml    deterministic   (§02.2b — the .yaml the grep misses)
 *   5. content/topics/queue.yaml           JUDGMENT   (one model call, deduped, human-reviewed)
 *   6. site/index.html + styles.css + robots.txt   deterministic  (§02.6 — THE SITE ITSELF)
 *   7. brand assets (favicon/icon/apple-touch/og.jpg)  deterministic
 *
 * There is no derive script in the reference build — this is new construction,
 * and 14 §B calls it "the one that decides whether you built a factory or a mold."
 *
 * FLAGS
 *   --only=voice|forbidden|links|authors|queue|site|assets|dashboard   (repeatable, comma-separated)
 *   --force      overwrite a hand-edited JUDGMENT artifact
 *   --append     queue only: generate N NEW topics and append (never rewrite)
 *   --count=N    with --append, how many new topics
 *   --dry-run    print what would regenerate + the estimated API call count, spend nothing
 *   --config=P   derive from a different config (used by the swap test)
 *
 * THE --force TRAP (§02, and it is subtle)
 * `queue.yaml` is ENGINE-MUTATED: dequeueTopic() rewrites it on every publish and
 * quarantineTopic() on every permanent failure. So on any live repo its hash stops
 * matching almost immediately, derive SKIPs it forever, and the only escape looks
 * like --force — which regenerates ~50 topics from scratch, re-adding already
 * published and quarantined slugs and breaking the ledger invariant. That is bug
 * A8 reborn. Reseeding is --append. --force on the queue is refused outright on a
 * repo with publish history.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { execFileSync } from 'child_process';
import { createHash } from 'crypto';
import yaml from 'js-yaml';
import { ROOT, cfg, contentPath, configHash, ConfigError, loadConfig } from './paths.mjs';
import { renderSite, BANNER } from './derive-site.mjs';
import { render } from './render-templates.mjs';
import { buildAuthor, authorPath } from './authors.mjs';
import { QUEUE_HEADER, YAML_OPTS, MAX_DERIVE_API_CALLS, BUCKETS } from './constants.mjs';
import { findNearDuplicateTopic } from './embed-similarity.mjs';
import { complete, stripFence, provider } from './model.mjs';
import { loadQueue, loadPublished, loadNeedsReview } from './pick-topic.mjs';

const BRAND_TPL = join(ROOT, 'templates', 'brand');
const ALL_STEPS = ['forbidden', 'links', 'authors', 'voice', 'queue', 'site', 'assets', 'workflows', 'dashboard'];
const JUDGMENT = new Set(['voice', 'queue']);

// ---------------------------------------------------------------------------
// API budget (§02 cost guard — mirrors R19). Advice is not a guard.
// ---------------------------------------------------------------------------
let apiCalls = 0;
function chargeApiCall(what) {
  apiCalls += 1;
  if (apiCalls > MAX_DERIVE_API_CALLS) {
    throw new Error(
      `derive API budget exhausted: ${apiCalls} > content.limits.max_derive_api_calls=` +
        `${MAX_DERIVE_API_CALLS} (tried: ${what}). Full re-derive is a new-business ` +
        'operation; use --only for routine changes.',
    );
  }
}

// ---------------------------------------------------------------------------
// Hand-edit guard (§02)
// ---------------------------------------------------------------------------

const HASH_RE = /derive-hash:\s*([a-f0-9]{16})/;

function contentHash(body) {
  return createHash('sha256').update(body.trim()).digest('hex').slice(0, 16);
}

function bannerFor(kind, cfgHash, bodyHash) {
  const c = kind === 'yaml' ? '#' : kind === 'css' ? ' *' : '#';
  return [
    `${c} ${BANNER}`,
    `${c} config-hash: ${cfgHash}`,
    `${c} derive-hash: ${bodyHash}`,
  ].join('\n');
}

/**
 * True when the file on disk was last written by derive and has not been touched
 * since. Refining a judgment artifact by hand is expected and good — the guard
 * exists to protect that work, not to forbid it.
 */
function isPristine(path) {
  if (!existsSync(path)) return true;
  const raw = readFileSync(path, 'utf8');
  const m = raw.match(HASH_RE);
  if (!m) return false;
  const body = raw.split('\n').filter((l) => !/^[#\s*]*(?:GENERATED by|config-hash:|derive-hash:)/.test(l)).join('\n');
  return contentHash(body) === m[1];
}

function writeGuarded(path, body, { kind = 'yaml', step, force, cfgSlice }) {
  const judgment = JUDGMENT.has(step);
  if (judgment && !force && !isPristine(path)) {
    console.log(`SKIP  ${rel(path)} (hand-edited; --force to overwrite)`);
    return false;
  }
  const head = bannerFor(kind, configHash(cfgSlice), contentHash(body));
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${head}\n${body.trim()}\n`, 'utf8');
  console.log(`WRITE ${rel(path)}`);
  return true;
}

const rel = (p) => p.replace(`${ROOT}/`, '');

/** Topic count of an existing queue file, for error messages only. */
function existsCountSafe(path) {
  try {
    const v = yaml.load(readFileSync(path, 'utf8'));
    return Array.isArray(v) ? v.length : 0;
  } catch {
    return 0;
  }
}
const existingCount = existsCountSafe;

// ---------------------------------------------------------------------------
// 2. forbidden.yaml — deterministic
// ---------------------------------------------------------------------------

export function buildForbidden(c) {
  const tpl = yaml.load(readFileSync(join(BRAND_TPL, 'forbidden.template.yaml'), 'utf8'));
  const phrases = new Set((tpl.phrases || []).map(String));
  const words = new Set((tpl.words || []).map(String));

  for (const b of c.brand.banned_extra || []) {
    (String(b).trim().includes(' ') ? phrases : words).add(String(b).trim());
  }

  // Compliance implies bans (R20). The prompt suggests; this enforces.
  const comp = c.compliance || {};
  if (comp.no_medical_claims) ['cures', 'heals', 'treats', 'medical-grade', 'clinically proven'].forEach((w) => words.add(w));
  if (comp.no_guarantees) {
    ['pain-free', 'completely painless', 'guaranteed results', 'risk-free'].forEach((p) => phrases.add(p));
    ['guaranteed', 'painless'].forEach((w) => words.add(w));
  }
  if (comp.no_superlatives_without_evidence) {
    ['the best', 'the ultimate', 'world-class', 'number one'].forEach((p) => phrases.add(p));
  }

  // Vertical-specific cringe. The reference banned "manscaping" because it was a
  // barbershop; a nail lounge needs a different list.
  const VERTICAL = {
    nail: ['mani-pedi', 'nail art goals'],
    lash: ['wispy', 'insta-lashes', 'flutter'],
    brow: ['brows on fleek', 'insta-brows'],
    wax: ['manscaping', 'down there', 'private parts'],
    barber: ['manscaping', 'fresh cut fade life'],
    spa: ['pamper', 'me-time', 'self-care journey'],
    massage: ['rubdown', 'happy ending'],
    tattoo: ['ink slinger', 'tramp stamp'],
  };
  const type = String(c.business.type).toLowerCase();
  for (const [k, list] of Object.entries(VERTICAL)) {
    if (type.includes(k)) list.forEach((t) => (t.includes(' ') ? phrases.add(t) : words.add(t)));
  }

  // A brand must not ban its own vocabulary — that would fail every article.
  const ownWords = new Set(
    [c.business.name, c.business.short_name, c.business.type, ...c.services.map((s) => s.label)]
      .join(' ').toLowerCase().split(/\s+/).filter(Boolean),
  );
  for (const w of [...words]) if (ownWords.has(w.toLowerCase())) words.delete(w);

  return yaml.dump(
    { phrases: [...phrases].sort(), words: [...words].sort() },
    { ...YAML_OPTS, sortKeys: false },
  );
}

// ---------------------------------------------------------------------------
// 3. internal-links.yaml — deterministic
// ---------------------------------------------------------------------------

export function buildInternalLinks(c) {
  const services = {};
  for (const s of c.services) {
    const label = s.label.toLowerCase();
    const variants = [
      label,
      `our ${label}`,
      `${label} in ${c.location.address_city}`,
    ];
    // Anchors must be distinct strings or the "one variant per target" rule is
    // unsatisfiable for the model.
    services[s.key] = { href: '/#services', variants: [...new Set(variants)] };
  }
  const brand = c.business.short_name;
  const city = c.location.address_city;
  const pages = {
    // "our <city> studio" was the reference's third variant. A barbershop is not
    // a studio and a nail bar is not a salon — a vertical-specific noun in a
    // generated anchor is a weld with extra steps. business.type is the only
    // place that word may come from.
    about: { href: '/#about', variants: [`about ${brand}`, `our ${c.business.type}`, `${brand} in ${city}`] },
    faq: { href: '/#faq', variants: ['common questions', 'frequently asked questions'] },
    aftercare: { href: '/#aftercare', variants: ['aftercare guide', 'post-visit care'] },
    visit: { href: '/#visit', variants: ['our location', 'directions and hours', `visit ${brand}`] },
  };
  return yaml.dump({ services, pages }, { ...YAML_OPTS, sortKeys: false });
}

// ---------------------------------------------------------------------------
// 1. voice.md — JUDGMENT (one model call)
// ---------------------------------------------------------------------------

/**
 * "Encino, Encino" is what you get when neighbourhood and city are the same
 * word and the template concatenates them anyway. Real single-neighbourhood
 * cities hit this constantly.
 */
function placeLine(c) {
  const n = c.location.neighborhood;
  const city = c.location.address_city;
  return n && n.toLowerCase() !== city.toLowerCase() ? `${n}, ${city}` : city;
}

/**
 * When no tenure was supplied, the prompt must FORBID inventing one rather than
 * simply omitting the fact. A model handed "Practitioner: Amir" and an eeat
 * topic bucket will reach for "years of experience" unless told not to.
 */
function tenureRule(c) {
  return c.derived.has_experience
    ? `- ${c.business.practitioner_name} has ${c.derived.experience_years} years of experience; you may reference it.`
    : `- NO length of experience has been supplied for ${c.business.practitioner_name}. Never state, imply or `
      + 'gesture at how long they have been working -- no "years of experience", no "decades", no '
      + '"since starting out", no "seasoned". Build authority from craft specifics instead.';
}

function voicePrompt(c) {
  const tpl = readFileSync(join(BRAND_TPL, 'voice.template.md'), 'utf8');
  const anchors = c.location.location_anchors;
  return `You are writing the authoritative brand-voice guide for a small personal-services business. This file is sent VERBATIM to a writing model on every article generation, so it is the single biggest lever on output quality.

Fill in the template below from the business facts. Replace every {{...}} placeholder with something concrete and opinionated. A vague voice file produces generic articles that then score as near-duplicates of each other and get quarantined forever — specificity is the whole point.

# The business
- Name: ${c.business.name} (short: ${c.business.short_name})
- Type: ${c.business.type}
- Positioning: ${c.business.positioning}
- Tagline: ${c.business.tagline}
- Practitioner: ${c.business.practitioner_name}${c.derived.has_experience ? `, ${c.derived.experience_years} years` : ''}
- Audience: ${c.brand.audience}
- Voice adjectives: ${c.brand.voice_adjectives.join(', ')}
- Feel (for VOICE only, not layout): ${c.brand.feel || '(none given)'}
- Where: ${placeLine(c)}, ${c.location.address_region}
- Services: ${c.services.map((s) => s.label).join(', ')}
- Booking: ${c.derived.booking_line}
- Phone published: ${c.booking.publish_phone === true ? 'YES' : 'NO'} · Email published: ${c.booking.publish_email === true ? 'YES' : 'NO'}
- Extra compliance notes: ${c.compliance?.extra_notes || '(none)'}
${tenureRule(c)}

# Structure numbers to state explicitly
- FAQ questions: ${c.content.faq_questions}
- Internal links: min ${c.content.internal_links.min}, max ${c.content.internal_links.max}
- Location mentions: min ${c.content.location_mentions_min}
- Word count: target ${c.content.word_count.target_min}-${c.content.word_count.target_max}, hard floor ${c.content.word_count.min}, ceiling ${c.content.word_count.max}
- Byline: "The ${c.business.short_name} Team"

# Prices you may reference
${c.services.map((s) => `- ${s.label}: ${s.price_from || '(no published price — the guide must say to omit it, never guess)'}`).join('\n')}

# Location vocabulary (group these sensibly under "Locations vocabulary")
${anchors.join(', ')}

# The template to fill
${tpl}

Rules:
- Output ONLY the finished markdown. No preamble, no code fence, no commentary.
- Keep every section heading from the template.
- The "Word choices" table must contain at least 5 preferred-vs-avoided pairs that are SPECIFIC TO THIS VERTICAL. Generic pairs are a failure.
- Do not invent facts. If a price is unknown, the guide must say to omit it.
- If the business does not publish a phone or email, the Contact policy section must FORBID writing one, not merely omit mention of it.`;
}

// ---------------------------------------------------------------------------
// 5. queue.yaml — JUDGMENT (one model call, then dedupe)
// ---------------------------------------------------------------------------

function queuePrompt(c, count, existingTitles) {
  const example = readFileSync(join(ROOT, 'templates', 'brand', 'queue.example.yaml'), 'utf8');
  const hyperCap = Math.floor(count * 0.3);
  return `Seed the editorial backlog for a ${c.business.type} in ${c.location.address_city}, ${c.location.address_region}.

Produce EXACTLY ${count} topics as a YAML array. Each topic:

- slug: kebab-case-unique
  title: "Human title, <= 65 chars where possible"
  target_keyword: the exact search phrase someone types
  secondary_keywords: ["variant 1", "variant 2"]
  intent: "TOF / informational" | "MOF / commercial" | "BOF / transactional"
  bucket: one of ${c.content.buckets.join(', ')}
  internal_links: [{ service: <key> }, { page: visit }]
  notes: "Angle guidance. THE MOST IMPORTANT FIELD."

# The business
- ${c.business.name}, ${c.business.type}, ${placeLine(c)}
- Practitioner: ${c.business.practitioner_name}${c.derived.has_experience ? `, ${c.derived.experience_years} years` : ''}
- Positioning: ${c.business.positioning}
- Audience: ${c.brand.audience}
${tenureRule(c)}

# Service keys you may use in internal_links
${c.services.map((s) => `- ${s.key} (${s.label})`).join('\n')}
Page keys: about, faq, aftercare, visit

# Real local anchors (use ONLY these — do not invent places)
${c.location.location_anchors.join(', ')}

# Keyword sourcing patterns
- hyperlocal: "[service] near [anchor]", "[service] in ${c.location.address_city}"
- service-detail: "what is [service]", "[service] what to expect"
- comparison: "[service] vs [alternative]"
- question: "does [service] hurt", "how long does [service] last", "how often should I..."
- aftercare: "after [service] care", "[problem] after [service]"
- pricing: "how much is [service] in ${c.location.address_city}"
- first-timer: "first [service] what to expect"
- eeat: ${c.derived.has_experience
    ? `"what ${c.derived.experience_years} years of [craft] taught ${c.business.practitioner_name}"`
    : '"why [technique] matters", "how a barber decides [judgement call]" — craft authority WITHOUT any claim about tenure'}

# THE ORIGINALITY TRAP — this is the part that usually fails
Hyperlocal topics are near-clones of each other. "[service] near A" and "[service] near B"
produce ~0.85+ similar articles and get quarantined forever. So:
1. Cap the hyperlocal bucket at ${hyperCap} of the ${count} topics. Spread the rest across the other buckets.
2. Every near-neighbour topic needs a genuinely DIFFERENT REASON TO EXIST in \`notes\` — not a
   different noun. "Local guide for [neighborhood]" is a failed note. State explicitly what
   framing the article must NOT reuse.
3. Put the strongest, most distinct topics FIRST — the queue publishes in order.

# Annotated GOOD vs BAD notes, read this before writing
${example}

${existingTitles.length ? `# Topics that ALREADY EXIST — do not duplicate these or anything close to them\n${existingTitles.map((t) => `- ${t}`).join('\n')}\n` : ''}
Output ONLY the YAML array. No preamble, no code fence, no commentary.`;
}

async function callModel(system, userMsg, what) {
  chargeApiCall(what);
  return complete({ system, user: userMsg, tag: what.replace(/\.(md|yaml)$/, '') });
}


/** Validate a model-produced topic list before it can reach the queue. */
export function validateTopics(topics, c) {
  const errors = [];
  if (!Array.isArray(topics)) return ['queue output is not a YAML array'];
  const seen = new Set();
  const serviceKeys = new Set(c.services.map((s) => s.key));
  const pageKeys = new Set(['about', 'faq', 'aftercare', 'visit']);
  topics.forEach((t, i) => {
    const at = `topics[${i}]`;
    for (const k of ['slug', 'title', 'target_keyword', 'intent', 'bucket', 'notes']) {
      if (!t?.[k]) errors.push(`${at}.${k} is missing`);
    }
    if (t?.slug) {
      if (!/^[a-z0-9-]+$/.test(t.slug)) errors.push(`${at}.slug "${t.slug}" is not kebab-case`);
      if (seen.has(t.slug)) errors.push(`${at}.slug "${t.slug}" is a duplicate`);
      seen.add(t.slug);
    }
    if (t?.bucket && !BUCKETS.includes(t.bucket)) {
      errors.push(`${at}.bucket "${t.bucket}" is not in content.buckets`);
    }
    // R13: a note that is not an angle is the failure mode this whole system has.
    if (t?.notes && String(t.notes).trim().length < 60) {
      errors.push(`${at}.notes is too thin (${String(t.notes).trim().length} chars) — it must state a reason to exist, not a subject`);
    }
    for (const l of t?.internal_links || []) {
      if (l.service && !serviceKeys.has(l.service)) errors.push(`${at} links unknown service "${l.service}"`);
      if (l.page && !pageKeys.has(l.page)) errors.push(`${at} links unknown page "${l.page}"`);
    }
  });
  const hyper = topics.filter((t) => t?.bucket === 'hyperlocal').length;
  if (topics.length && hyper / topics.length > 0.35) {
    errors.push(`hyperlocal is ${Math.round((hyper / topics.length) * 100)}% of the queue (cap ~30%, R13)`);
  }
  return errors;
}

/** R13 — dedupe at the SEED gate, which is stricter than the publish gate. */
async function dedupeTopics(topics, existing, c) {
  const kept = [];
  const dropped = [];
  for (const t of topics) {
    const dup = await findNearDuplicateTopic(t, {
      threshold: c.content.queue_dedupe_max_similarity,
      queueTopics: [...existing, ...kept],
      excludeSlug: t.slug,
    });
    if (dup) dropped.push({ slug: t.slug, near: dup });
    else kept.push(t);
  }
  return { kept, dropped };
}

// ---------------------------------------------------------------------------
// 7 + dashboard mirror
// ---------------------------------------------------------------------------

const DAY_CRON = {
  Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6,
};

/**
 * UTC hour for a local wall-clock time in a given IANA zone, on a given date.
 * Run for both January and July so DST is covered explicitly rather than by a
 * comment saying it drifts.
 */
function utcHourFor(tz, hhmm, monthIndex) {
  const [h, m] = hhmm.split(':').map(Number);
  // Find the UTC instant whose local time in `tz` is h:m on that date.
  const probe = new Date(Date.UTC(2026, monthIndex, 15, 12, 0, 0));
  const fmt = new Intl.DateTimeFormat('en-US', {
    timeZone: tz, hour: 'numeric', hour12: false, timeZoneName: 'longOffset',
  });
  const name = fmt.formatToParts(probe).find((p) => p.type === 'timeZoneName')?.value || 'GMT+00:00';
  const sign = name.includes('-') ? -1 : 1;
  const [oh, om] = name.replace(/GMT[+-]?/, '').split(':').map((x) => Number(x || 0));
  const offsetMinutes = sign * ((oh || 0) * 60 + (om || 0));
  let total = h * 60 + m - offsetMinutes;
  let dayShift = 0;
  while (total < 0) { total += 1440; dayShift -= 1; }
  while (total >= 1440) { total -= 1440; dayShift += 1; }
  return { hour: Math.floor(total / 60), minute: total % 60, dayShift };
}

/**
 * Emit the publish crons. A12 / §14 C1: the cadence lives in four places and
 * hand-editing one is how "next publish" starts lying.
 */
export function buildCronLines(c) {
  const tz = c.location.timezone;
  const hhmm = c.content.publish_hour_local;
  const lines = [];
  const seen = new Set();
  for (const monthIndex of [0, 6]) {          // January (standard), July (daylight)
    const { hour, minute, dayShift } = utcHourFor(tz, hhmm, monthIndex);
    // An odd minute keeps us out of the :00 congestion GitHub warns about.
    const min = (minute + 23) % 60;
    const days = c.content.cadence_days
      .map((d) => (DAY_CRON[d] + dayShift + 7) % 7)
      .sort((a, b) => a - b)
      .join(',');
    const cron = `${min} ${hour} * * ${days}`;
    if (seen.has(cron)) continue;
    seen.add(cron);
    lines.push(`    - cron: '${cron}'   # ${hhmm} ${tz}, ${monthIndex === 0 ? 'standard time' : 'daylight time'}`);
  }
  return lines.join('\n');
}

function buildWorkflows(c) {
  const src = join(ROOT, 'templates', 'workflows');
  const dest = join(ROOT, '.github', 'workflows');
  mkdirSync(dest, { recursive: true });
  const vars = {
    ...c,
    CRON_LINES: buildCronLines(c),
    // Weekly health check, deliberately offset from any publish slot.
    HEALTH_CRON: `37 ${(utcHourFor(c.location.timezone, c.content.publish_hour_local, 6).hour + 6) % 24} * * 3`,
  };
  const written = [];
  for (const f of readdirSync(src)) {
    if (!f.endsWith('.yml')) continue;
    const out = render(readFileSync(join(src, f), 'utf8'), vars, { name: `workflow:${f}`, strict: false });
    writeFileSync(join(dest, f), out, 'utf8');
    written.push(`.github/workflows/${f}`);
  }
  return written;
}

function buildDashboardConstants(c) {
  const j = (v) => JSON.stringify(v, null, 2);
  return `/* ${BANNER}
 *
 * Fixes bugs A10/A11/A12. The reference dashboard kept its OWN copies of the
 * queue header (which drifted, so engine and dashboard writes reformatted the
 * file back and forth forever), of BUCKETS (11 entries vs the config's 8, so
 * validateTopic silently rejected valid topics), and of the publish cadence
 * (hardcoded Mon/Thu 09:00 America/Los_Angeles, so "next publish" lied the
 * moment anyone changed the schedule). They are generated from one source now.
 */
export const QUEUE_HEADER = ${j(QUEUE_HEADER)};
export const BUCKETS = ${j(c.content.buckets)};
export const INTENTS = ${j(['TOF / informational', 'MOF / commercial', 'BOF / transactional'])};
export const SERVICE_KEYS = ${j(c.services.map((s) => s.key))};
export const PAGE_KEYS = ${j(['about', 'faq', 'aftercare', 'visit'])};
export const CADENCE_DAYS = ${j(c.content.cadence_days)};
export const PUBLISH_HOUR_LOCAL = ${j(c.content.publish_hour_local)};
export const TIMEZONE = ${j(c.location.timezone)};
export const LIVE_URL = ${j(c.derived.site_url)};
export const BUSINESS_NAME = ${j(c.business.name)};
export const AUTHOR_ID = ${j(c.business.author_id)};
`;
}

function runAssets(c, dryRun) {
  if (dryRun) { console.log('DRY   assets (python3 scripts/generate-assets.py)'); return; }
  try {
    const out = execFileSync('python3', [join(ROOT, 'scripts', 'generate-assets.py')], {
      cwd: ROOT, encoding: 'utf8', env: { ...process.env },
    });
    console.log(out.trim().split('\n').map((l) => `      ${l}`).join('\n'));
  } catch (e) {
    throw new Error(
      `Asset generation failed. The generator is Python + Pillow, not Node — a machine ` +
        `without them is a silent failure inside an otherwise-npm workflow (§02.5).\n` +
        `Install with: pip install Pillow\n${e.stderr || e.message}`,
    );
  }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const only = [];
  let force = false; let append = false; let dryRun = false; let count = null; let config = null;
  for (const a of argv) {
    if (a.startsWith('--only=')) only.push(...a.slice(7).split(',').map((s) => s.trim()).filter(Boolean));
    else if (a === '--force') force = true;
    else if (a === '--append') append = true;
    else if (a === '--dry-run') dryRun = true;
    else if (a.startsWith('--count=')) count = Number(a.slice(8));
    else if (a.startsWith('--config=')) config = a.slice(9);
  }
  const bad = only.filter((s) => !ALL_STEPS.includes(s));
  if (bad.length) throw new Error(`Unknown --only step(s): ${bad.join(', ')}. Known: ${ALL_STEPS.join(', ')}`);
  return { steps: only.length ? only : ALL_STEPS, force, append, dryRun, count, config };
}

export async function derive(argv = process.argv.slice(2)) {
  const { steps, force, append, dryRun, count, config } = parseArgs(argv);
  const c = config ? loadConfig(config.startsWith('/') ? config : join(ROOT, config)) : cfg;

  const willCallApi = steps.filter((s) => JUDGMENT.has(s));
  console.log(`derive: ${c.business.name} — steps: ${steps.join(', ')}`);
  if (dryRun) {
    console.log(`DRY RUN — no files written, no API calls made.`);
    console.log(`Model provider: ${provider() || 'NONE — judgment artifacts will fail'}`);
    console.log(`Estimated model calls: ${willCallApi.length} (cap ${MAX_DERIVE_API_CALLS})`);
    for (const s of steps) {
      const j = JUDGMENT.has(s);
      console.log(`  ${j ? 'API ' : 'PURE'}  ${s}${j ? ' (judgment — model call + human review)' : ''}`);
    }
    return { dryRun: true, steps };
  }

  const slice = { business: c.business, location: c.location, brand: c.brand, content: c.content, services: c.services };

  for (const step of steps) {
    switch (step) {
      case 'forbidden':
        writeGuarded(contentPath('brand', 'forbidden.yaml'), buildForbidden(c), { step, force, cfgSlice: slice });
        break;

      case 'links':
        writeGuarded(contentPath('brand', 'internal-links.yaml'), buildInternalLinks(c), { step, force, cfgSlice: slice });
        break;

      case 'authors':
        writeGuarded(authorPath(c.business.author_id), yaml.dump(buildAuthor(c), YAML_OPTS), { step, force, cfgSlice: slice });
        break;

      case 'voice': {
        const path = contentPath('brand', 'voice.md');
        if (!force && existsSync(path) && !isPristine(path)) {
          console.log(`SKIP  ${rel(path)} (hand-edited; --force to overwrite)`);
          break;
        }
        const md = stripFence(await callModel(
          'You write brand-voice guides for small service businesses. You are concrete and opinionated, never generic.',
          voicePrompt(c), 'voice.md',
        ));
        writeGuarded(path, md, { kind: 'md', step, force: true, cfgSlice: slice });
        break;
      }

      case 'queue': {
        await deriveQueue(c, { force, append, count, slice });
        break;
      }

      case 'site':
        await renderSite(c);
        console.log('WRITE site/index.html\nWRITE site/assets/styles.css\nWRITE site/robots.txt');
        break;

      case 'assets':
        runAssets(c, dryRun);
        break;

      case 'workflows':
        for (const f of buildWorkflows(c)) console.log(`WRITE ${f}`);
        break;

      case 'dashboard': {
        const p = join(ROOT, 'dashboard', 'lib', 'generated-constants.ts');
        if (existsSync(join(ROOT, 'dashboard'))) {
          mkdirSync(dirname(p), { recursive: true });
          writeFileSync(p, buildDashboardConstants(c), 'utf8');
          console.log(`WRITE ${rel(p)}`);
        } else {
          console.log('SKIP  dashboard/ (not present)');
        }
        break;
      }
      default:
        break;
    }
  }

  console.log(`\nderive complete. API calls used: ${apiCalls}/${MAX_DERIVE_API_CALLS}`);
  return { steps, apiCalls };
}

async function deriveQueue(c, { force, append, count, slice }) {
  const path = contentPath('topics', 'queue.yaml');
  const exists = existsSync(path);
  const published = exists ? (loadPublished().entries || []) : [];
  const quarantined = exists ? (loadNeedsReview().entries || []) : [];
  const hasHistory = published.length > 0 || quarantined.length > 0;

  if (force && hasHistory && !append) {
    throw new Error(
      'REFUSING --force on queue.yaml: this repo has publish history ' +
        `(${published.length} published, ${quarantined.length} quarantined).\n` +
        'Regenerating from scratch would re-add already-published and quarantined slugs and\n' +
        'break the ledger invariant (every topic in exactly ONE of queue/published/needs-review).\n' +
        'That is bug A8 reborn. Use `--only=queue --append --count=N` to add runway instead.\n' +
        '--force on the queue is a NEW-BUSINESS operation only.',
    );
  }

  // The queue is a LEDGER, not a rendered artifact: `publish-article.mjs`
  // removes a slug from it on success, so an overwrite is not idempotent — it
  // silently resurrects work already done. Every other JUDGMENT artifact is
  // protected by the derive-hash banner; the queue cannot carry one (its own
  // consumers rewrite it), so the protection has to be an explicit gate.
  if (exists && !force && !append) {
    throw new Error(
      `REFUSING to overwrite an existing queue.yaml (${existingCount(path)} topics).\n`
        + 'The queue is a ledger that publish-article.mjs mutates, so a plain rewrite is\n'
        + 'destructive rather than idempotent.\n'
        + '  --only=queue --append --count=N   add runway to the end (the normal operation)\n'
        + '  --only=queue --force              reseed from scratch (new business only)',
    );
  }

  const existingQueue = exists ? loadQueue() : [];
  const existingTitles = [
    ...existingQueue.map((t) => t.title),
    ...published.map((e) => e.title),
    ...quarantined.map((e) => e.title),
  ].filter(Boolean);

  const want = count || (append ? 10 : c.content.topics_to_seed);
  const raw = stripFence(await callModel(
    'You are an SEO editorial planner for small local service businesses. You produce topics with genuinely distinct angles, never interchangeable ones.',
    queuePrompt(c, want, existingTitles), 'queue.yaml',
  ));

  let topics;
  try {
    topics = yaml.load(raw);
  } catch (e) {
    throw new Error(`Model returned unparseable YAML for the queue: ${e.message}`);
  }

  const errors = validateTopics(topics, c);
  if (errors.length) {
    throw new Error(`Generated queue failed validation:\n${errors.map((e) => `  • ${e}`).join('\n')}`);
  }

  const { kept, dropped } = await dedupeTopics(topics, existingQueue, c);
  if (dropped.length) {
    console.log(`      deduped out ${dropped.length} topic(s) at >${c.content.queue_dedupe_max_similarity}:`);
    for (const d of dropped) console.log(`        - ${d.slug} (near ${d.near})`);
  }

  // content/topics/ does not exist in a fresh clone — the template ships
  // content/{articles,authors,brand} because those have committed files, and a
  // queue is by definition generated. Without this, EVERY new business dies on
  // ENOENT after the model call has already been spent.
  mkdirSync(dirname(path), { recursive: true });

  if (append) {
    // NEVER rewrite an existing entry (§02.4).
    const final = [...existingQueue, ...kept];
    writeFileSync(path, QUEUE_HEADER + yaml.dump(final, YAML_OPTS), 'utf8');
    console.log(`WRITE ${rel(path)} (appended ${kept.length}; ${final.length} total)`);
  } else {
    writeFileSync(path, QUEUE_HEADER + yaml.dump(kept, YAML_OPTS), 'utf8');
    console.log(`WRITE ${rel(path)} (${kept.length} topics)`);
  }
  const hyper = kept.filter((t) => t.bucket === 'hyperlocal').length;
  console.log(`      hyperlocal: ${hyper}/${kept.length} (${Math.round((hyper / Math.max(kept.length, 1)) * 100)}%, cap ~30%)`);
}

const invoked = process.argv[1] && process.argv[1].endsWith('derive.mjs');
if (invoked) {
  derive().catch((e) => {
    console.error(`\n${e.message}`);
    process.exit(1);
  });
}
