/**
 * derive-site.mjs — renders THE SITE ITSELF from business.config.yaml.
 *
 * 02-DERIVE-BRAIN.md §6: "This is the artifact everyone forgets, and skipping it
 * silently voids the entire factory." The reference `build-blog.mjs` never wrote
 * site/index.html or styles.css at all — they were committed, hand-authored,
 * one-business artifacts. If you derive only the brain, the swap test yields
 * business #2's blog bolted onto business #1's homepage, in business #1's
 * colours, with business #1's address in the footer of every article. It looks
 * like it worked. It is worthless.
 *
 * Outputs (all deterministic — no API call, byte-identical every run):
 *   site/index.html
 *   site/assets/styles.css
 *   robots.txt
 *
 * Never hand-edit any of the three. They are output.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { render, loadPartials, escapeHtml } from './render-templates.mjs';
import { ROOT, configHash } from './paths.mjs';
import { buildTokens, getVariant, contrastRatio, isDarkTheme } from './layout-variants.mjs';

const TEMPLATES = join(ROOT, 'templates');
const SECTIONS = join(TEMPLATES, 'sections');
const SITE = join(ROOT, 'site');

export const BANNER =
  'GENERATED by npm run derive from business.config.yaml — see 02-DERIVE-BRAIN.md. DO NOT HAND-EDIT.';

// ---------------------------------------------------------------------------
// Google Fonts
// ---------------------------------------------------------------------------

export function fontsHref(cfg) {
  const fams = [cfg.brand.fonts.display, cfg.brand.fonts.body]
    .map((f) => `family=${f.trim().replace(/\s+/g, '+')}:wght@300;400;500;600;700`)
    .join('&');
  return `https://fonts.googleapis.com/css2?${fams}&display=swap`;
}

// ---------------------------------------------------------------------------
// Structured data (07 §C)
// ---------------------------------------------------------------------------

export function localBusinessJsonLd(cfg) {
  const { business: b, location: loc, hours, derived } = cfg;
  const ld = {
    '@context': 'https://schema.org',
    '@type': b.category_schema,
    name: b.name,
    url: derived.site_url,
    image: derived.og_image_url,
    logo: derived.logo_url,
    description: b.positioning,
    address: {
      '@type': 'PostalAddress',
      streetAddress: loc.address_street,
      addressLocality: loc.address_city,
      addressRegion: loc.address_region,
      postalCode: loc.address_postal,
      addressCountry: loc.address_country,
    },
    openingHoursSpecification: [{
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: hours.days,
      opens: hours.opens,
      closes: hours.closes,
    }],
    areaServed: loc.address_city,
  };
  // priceRange only when we actually have prices — never invent one.
  const priced = (cfg.services || []).filter((s) => s.price_from);
  if (priced.length) ld.priceRange = priceRange(priced);
  // R20 / 04 §A: telephone appears ONLY when the business publishes it.
  if (cfg.booking.publish_phone === true) ld.telephone = cfg.booking.phone;
  if (cfg.booking.publish_email === true) ld.email = cfg.booking.email;
  if (cfg.booking.url) ld.hasMap = derived.address_maps_url;
  return ld;
}

function priceRange(priced) {
  const nums = priced
    .map((s) => Number(String(s.price_from).replace(/[^0-9.]/g, '')))
    .filter((n) => Number.isFinite(n) && n > 0);
  if (!nums.length) return undefined;
  const lo = Math.min(...nums);
  const bucket = (n) => (n < 50 ? '$' : n < 120 ? '$$' : n < 250 ? '$$$' : '$$$$');
  const hi = Math.max(...nums);
  return bucket(lo) === bucket(hi) ? bucket(lo) : `${bucket(lo)}-${bucket(hi)}`;
}

export function faqPageJsonLd(cfg) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: cfg.homepage.faq.map((f) => ({
      '@type': 'Question',
      name: f.q,
      acceptedAnswer: { '@type': 'Answer', text: f.a },
    })),
  };
}

// ---------------------------------------------------------------------------
// The contact assertion — 04 §A, verbatim: "Never leave this to a human eyeball —
// that's how a client's private number ends up indexed."
// ---------------------------------------------------------------------------

const PHONE_RE = /(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/;
const EMAIL_RE = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/i;

export function assertNoLeakedContact(html, cfg, label) {
  const problems = [];
  if (cfg.booking.publish_phone !== true) {
    if (/tel:/i.test(html)) problems.push('a tel: link');
    // Strip things that legitimately contain digit runs before scanning.
    const scrub = html
      .replace(/<script[\s\S]*?<\/script>/gi, '')
      .replace(/<style[\s\S]*?<\/style>/gi, '')
      .replace(/https?:\/\/\S+/gi, '')
      .replace(/[a-z-]+="[^"]*"/gi, ' ');
    const m = scrub.match(PHONE_RE);
    if (m) problems.push(`a phone-shaped digit run ("${m[0].trim()}")`);
  }
  if (cfg.booking.publish_email !== true) {
    const scrub = html.replace(/<script[\s\S]*?<\/script>/gi, '');
    if (/mailto:/i.test(scrub)) problems.push('a mailto: link');
    const m = scrub.replace(/<[^>]+>/g, ' ').match(EMAIL_RE);
    if (m) problems.push(`an email address ("${m[0]}")`);
  }
  if (problems.length) {
    throw new Error(
      `CONTACT LEAK in ${label}: found ${problems.join(' and ')}, but the config says ` +
        `publish_phone=${cfg.booking.publish_phone} publish_email=${cfg.booking.publish_email}.\n` +
        'A published private number is not a cosmetic bug — the build fails here on purpose (04 §A).',
    );
  }
}

/** Nothing from another business may survive into the rendered site (§02.6 exit). */
const REFERENCE_FACTS = [
  'Igor For Men', 'igorformen.com', 'West Hollywood', 'Larrabee', "Rene'", '90069', 'IFM',
];

export function assertNoForeignFacts(html, cfg, label) {
  const own = new Set([
    cfg.business.name, cfg.business.short_name, cfg.business.initials,
    cfg.location.address_city, cfg.site.domain,
  ].map((s) => String(s).toLowerCase()));
  const hits = REFERENCE_FACTS.filter(
    (f) => !own.has(f.toLowerCase()) && new RegExp(`\\b${f.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(html),
  );
  if (hits.length) {
    throw new Error(
      `FOREIGN BUSINESS FACT in ${label}: ${hits.join(', ')}. ` +
        'That is an uncut weld — a hardcoded fact from the reference build (14 §C).',
    );
  }
}

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function tokenBlock(cfg) {
  const tokens = buildTokens(cfg);
  return Object.entries(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
}

function sectionTone(cfg, variant, id) {
  return variant.darkSections.includes(id) ? 'section--dark' : '';
}

function headAlign(variant) {
  return ['gallery', 'classic'].includes(variant.label) ? 'section__head--center' : '';
}

export async function renderSite(cfg, { write = true } = {}) {
  const variant = getVariant(cfg.brand.layout_variant);
  const partials = await loadPartials(ROOT);
  const anchors = cfg.location.location_anchors;

  const baseVars = {
    ...cfg,
    THEME: isDarkTheme(cfg) ? 'dark' : 'light',
    FONTS_HREF: fontsHref(cfg),
    HOME_HREF: '/',
    NAV_JOURNAL_ACTIVE: false,
    SERVICE_COUNT: String(cfg.services.length),
    ANCHOR_1: anchors[0],
    ANCHOR_2: anchors[1],
    ANCHOR_3: anchors[2] || anchors[0],
    NEARBY: anchors.slice(0, 6),
    GENERATED_BANNER: BANNER,
  };

  const opts = { partials, name: 'site' };

  // --- sections, in the variant's order, using the variant's markup ---
  const sectionHtml = variant.order.map((id) => {
    const tplName = variant.sections[id];
    const file = join(SECTIONS, `${tplName}.html`);
    if (!existsSync(file)) {
      throw new Error(
        `layout_variant "${variant.label}" wants section template "${tplName}.html" ` +
          `for section "${id}", but ${file} does not exist.`,
      );
    }
    const tpl = readFileSync(file, 'utf8');
    return render(tpl, {
      ...baseVars,
      SECTION_TONE: sectionTone(cfg, variant, id),
      HEAD_ALIGN: headAlign(variant),
      // per-service initial for the gallery card media
      services: cfg.services.map((s) => ({ ...s, INITIAL: s.label.trim().charAt(0).toUpperCase() })),
    }, { ...opts, name: `section:${tplName}` });
  }).join('\n');

  // --- head ---
  const jsonLd = [localBusinessJsonLd(cfg), faqPageJsonLd(cfg)];
  const extraHead = [
    `<link rel="canonical" href="${cfg.derived.site_url}/" />`,
    `<meta property="og:title" content="${escapeHtml(cfg.derived.meta_title)}" />`,
    `<meta property="og:description" content="${escapeHtml(cfg.derived.meta_description)}" />`,
    '<meta property="og:type" content="website" />',
    `<meta property="og:url" content="${cfg.derived.site_url}/" />`,
    `<meta property="og:image" content="${cfg.derived.og_image_url}" />`,
    '<meta property="og:image:width" content="1200" />',
    '<meta property="og:image:height" content="630" />',
    `<meta property="og:site_name" content="${escapeHtml(cfg.business.name)}" />`,
    '<meta name="twitter:card" content="summary_large_image" />',
    `<meta name="twitter:title" content="${escapeHtml(cfg.derived.meta_title)}" />`,
    `<meta name="twitter:description" content="${escapeHtml(cfg.derived.meta_description)}" />`,
    `<meta name="twitter:image" content="${cfg.derived.og_image_url}" />`,
    ...jsonLd.map((o) => `<script type="application/ld+json">${JSON.stringify(o)}</script>`),
  ].join('\n');

  const headHtml = render(partials.head, {
    ...baseVars,
    PAGE_TITLE: cfg.derived.meta_title,
    META_DESC: cfg.derived.meta_description,
    EXTRA_HEAD: extraHead,
  }, { ...opts, name: 'partial:head' });

  const topbarHtml = render(partials.topbar, baseVars, { ...opts, name: 'partial:topbar' });
  const navHtml = render(partials.nav, baseVars, { ...opts, name: 'partial:nav' });
  const footerHtml = render(partials.footer, baseVars, { ...opts, name: 'partial:footer' });

  const pageTpl = readFileSync(join(TEMPLATES, 'page.html'), 'utf8');
  let indexHtml = render(pageTpl, {
    ...baseVars,
    HEAD: headHtml,
    TOPBAR: topbarHtml,
    NAV: navHtml,
    SECTIONS: sectionHtml,
    FOOTER: footerHtml,
  }, { ...opts, name: 'page' });

  indexHtml = `<!-- ${BANNER} -->\n${indexHtml}`;

  // --- stylesheet ---
  const cssTpl = readFileSync(join(TEMPLATES, 'styles.css'), 'utf8');
  const css = render(cssTpl, {
    ...baseVars,
    TOKEN_BLOCK: tokenBlock(cfg),
    IS_EDITORIAL: variant.label === 'editorial',
    IS_COMPACT: variant.label === 'compact',
    IS_GALLERY: variant.label === 'gallery',
    IS_CLASSIC: variant.label === 'classic',
  }, { ...opts, name: 'styles.css' });

  // --- robots.txt (R21: derive renders it; build-blog must never write it) ---
  const robotsTpl = readFileSync(join(ROOT, 'templates', 'robots.txt'), 'utf8');
  const robots = render(robotsTpl, baseVars, { ...opts, name: 'robots.txt' });

  // --- gates ---
  assertNoLeakedContact(indexHtml, cfg, 'site/index.html');
  assertNoForeignFacts(indexHtml, cfg, 'site/index.html');
  assertNoForeignFacts(css, cfg, 'site/assets/styles.css');
  assertNoForeignFacts(robots, cfg, 'robots.txt');
  assertContrast(cfg);

  if (write) {
    mkdirSync(join(SITE, 'assets'), { recursive: true });
    writeFileSync(join(SITE, 'index.html'), indexHtml, 'utf8');
    writeFileSync(join(SITE, 'assets', 'styles.css'), css, 'utf8');
    writeFileSync(join(ROOT, 'robots.txt'), robots, 'utf8');
  }

  return { indexHtml, css, robots, hash: configHash({ ...cfg, derived: undefined }) };
}

/** 04 §E: contrast is non-negotiable. A brand palette that fails AA fails the build. */
export function assertContrast(cfg) {
  const p = cfg.brand.palette;
  const checks = [
    ['text on bg', p.text, p.bg, 4.5],
    ['muted on bg', p.muted, p.bg, 4.5],
    ['text on surface', p.text, p.surface, 4.5],
    ['accent on bg', p.accent, p.bg, 3.0],
  ];
  const failures = checks
    .map(([label, a, b, min]) => [label, contrastRatio(a, b), min])
    .filter(([, ratio, min]) => ratio < min);
  if (failures.length) {
    throw new Error(
      'PALETTE FAILS WCAG AA:\n' +
        failures.map(([l, r, m]) => `  • ${l}: ${r.toFixed(2)}:1 (needs ${m}:1)`).join('\n') +
        '\nAdjust brand.palette in business.config.yaml. 04 §E: contrast is non-negotiable.',
    );
  }
}
